# Generated by Django 3.0.5 on 2022-08-11 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0008_auto_20220811_1154'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expens',
            name='price',
        ),
        migrations.RemoveField(
            model_name='income',
            name='price',
        ),
        migrations.AddField(
            model_name='expens',
            name='is_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='income',
            name='is_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
