# Generated by Django 3.0.5 on 2022-08-11 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0009_auto_20220811_1157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expens',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='income',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
