# Generated by Django 3.0.5 on 2022-08-11 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0011_auto_20220811_1201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expens',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='expens',
            name='todo',
            field=models.ForeignKey(default=11, on_delete=django.db.models.deletion.CASCADE, related_name='expens', to='todo.Todo'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='income',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='income',
            name='todo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='income', to='todo.Todo'),
            preserve_default=False,
        ),
    ]
